USE [master]
GO
DROP DATABASE TrabajoGI1819
GO
CREATE DATABASE TrabajoGI1819
GO
USE [TrabajoGI1819]
GO
/****** Object:  Table [dbo].[tPermiso]    Script Date: 31/10/2018 11:54:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tPermiso](
  [rolName] [varchar](50) NOT NULL,
  [pantalla] [varchar](50) NOT NULL,
  [acceso] [bit] NOT NULL,
  [modificacion] [bit] NOT NULL,
  CONSTRAINT [PK_tPermiso] PRIMARY KEY CLUSTERED
    (
      [rolName] ASC,
      [pantalla] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tPiezas]    Script Date: 31/10/2018 11:54:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tPiezas](
  [ID] [int] IDENTITY(1,1) NOT NULL,
  [NOMBRE] [varchar](255) NOT NULL,
  [FABRICANTE] [varchar](255) NOT NULL,
  [ID_TIPO] [varchar](4) NOT NULL,
  CONSTRAINT [PK_Pieza] PRIMARY KEY CLUSTERED
    (
      [ID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tRol]    Script Date: 31/10/2018 11:54:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tRol](
  [rolName] [varchar](50) NOT NULL,
  [rolDes] [varchar](255) NULL,
  [admin] [bit] NOT NULL,
  CONSTRAINT [PK_tRol] PRIMARY KEY CLUSTERED
    (
      [rolName] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tTipoPieza]    Script Date: 31/10/2018 11:54:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tTipoPieza](
  [ID_TIPO] [varchar](4) NOT NULL,
  [NOMBRE] [varchar](80) NOT NULL,
  CONSTRAINT [PK_tTipoPieza] PRIMARY KEY CLUSTERED
    (
      [ID_TIPO] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tUsuario]    Script Date: 31/10/2018 11:54:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tUsuario](
  [nombre] [varchar](50) NOT NULL,
  [password] [varchar](50) NOT NULL,
  [rolName] [varchar](50) NOT NULL,
  CONSTRAINT [PK_tUsuario] PRIMARY KEY CLUSTERED
    (
      [nombre] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[tPermiso]  WITH CHECK ADD  CONSTRAINT [FK_tPermiso_tRol] FOREIGN KEY([rolName])
REFERENCES [dbo].[tRol] ([rolName])
GO
ALTER TABLE [dbo].[tPermiso] CHECK CONSTRAINT [FK_tPermiso_tRol]
GO
ALTER TABLE [dbo].[tPiezas]  WITH CHECK ADD  CONSTRAINT [FK_tPiezas_tTipoPieza] FOREIGN KEY([ID_TIPO])
REFERENCES [dbo].[tTipoPieza] ([ID_TIPO])
  ON UPDATE CASCADE
  ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tPiezas] CHECK CONSTRAINT [FK_tPiezas_tTipoPieza]
GO
ALTER TABLE [dbo].[tUsuario]  WITH CHECK ADD  CONSTRAINT [FK_tUsuario_tRol] FOREIGN KEY([rolName])
REFERENCES [dbo].[tRol] ([rolName])
  ON UPDATE CASCADE
  ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tUsuario] CHECK CONSTRAINT [FK_tUsuario_tRol]
GO

DELETE tRol;
INSERT INTO tRol VALUES('administrador', 'administrador',1);
INSERT INTO tRol VALUES('usuario', 'usuario',0);
INSERT INTO tRol VALUES('invitado', 'invitado',0);
GO

DELETE tUsuario;
GO
INSERT INTO tUsuario VALUES('admin', 'admin','administrador');
INSERT INTO tUsuario VALUES('user', 'user','usuario');
INSERT INTO tUsuario VALUES('inv', 'inv','invitado');
GO

DELETE tPermiso;
GO
INSERT INTO tPermiso VALUES('administrador','LOGIN',1,1);
INSERT INTO tPermiso VALUES('administrador','MATERIAS',1,1);
INSERT INTO tPermiso VALUES('administrador','LIBROS',1,1);

INSERT INTO tPermiso VALUES('usuario','LOGIN',1,1);
INSERT INTO tPermiso VALUES('usuario','MATERIAS',1,0);
INSERT INTO tPermiso VALUES('usuario','LIBROS',1,0);

INSERT INTO tPermiso VALUES('invitado','LOGIN',1,1);
INSERT INTO tPermiso VALUES('invitado','MATERIAS',0,0);
INSERT INTO tPermiso VALUES('invitado','LIBROS',0,0);

GO

Delete FROM [tTipoPieza];
GO

INSERT INTO tTipoPieza VALUES('A','Chapa');
INSERT INTO tTipoPieza VALUES('B','Motor');
INSERT INTO tTipoPieza VALUES('C','Iluminaci�n');
INSERT INTO tTipoPieza VALUES('D','Sensores');
INSERT INTO tTipoPieza VALUES('E','Cristales');
INSERT INTO tTipoPieza VALUES('F','Pintura');
INSERT INTO tTipoPieza VALUES('G','Otros');


GO

INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('PARAGOLPES DELANTERO NEGRO-LISO A IMPRIMAR','MAZDA','A');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('PARAGOLPES TRASERO-IMPRIMADO','MAZDA','A');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('REJILLA NEGRA','MAZDA','A');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('ALETA DELANTERA DCH CON AUJERO PARA PILOTO CX3 16','MAZDA','A');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('ALETA DELANTERA IZQ CON AUJERO PARA PILOTO CX3 16','MAZDA','A');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Bombillas luz delantera','RENAULT','C');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Bombillas se�alizaci�n delantera','RENAULT','C');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Bombillas luz trasera','RENAULT','C');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Bombillas se�alizaci�n trasera','RENAULT','C');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Estuches de bombillas','RENAULT','C');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Iluminaci�n LED','RENAULT','C');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Bombillas interior','RENAULT','C');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Bombillas Xenon','RENAULT','C');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Juntas y otras piezas del motor','FORD','B');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Alimentaci�n','FORD','B');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Kits de distribuci�n','FORD','B');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Correas','FORD','B');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Poleas','FORD','B');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Kits','FORD','B');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('V�lvulas EGR','FORD','B');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Herramienta espec�fica','FORD','B');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Turbocompresores','FORD','B');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Sensores electr�nicos y medidores de flujo','FORD','B');
INSERT INTO tPiezas(NOMBRE,FABRICANTE,ID_TIPO) VALUES('Cable de acelerador y starter','FORD','B');
GO
